use_frameworks!

platform :ios, '9.0'

target 'NBLShareView_Example' do
  pod 'NBLShareView', :path => '../'

  target 'NBLShareView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
